### ISSUE TITLE
Transfer Listo to it's own org

### ISSUE THREAD

**Issue by mr-beerkiss** [seek-oss/listo#51]
SEEK no longer uses Listo for security assessments. We still believe in the underlying intent of the tool, but we lacked the resources to support and operate it and thus it was poorly adopted and offered little value to engineering teams and the business.

This issue proposes moving Listo to its own org so it continues to be available for other teams or organisations that might be dependent on it. 

I'd appreciate any feedback from the community that may be using this tool to help improve their security posture. Alternatively, if there is little active use we can archive Listo and leave it open for someone else to fork and maintain.

Thoughts @bertonjulian and @zsims ?

**Comment by bertonjulian** [comment]
Hey @mr-beerkiss! Makes sense to archive, unless someone else wants to keep maintaining it. I don't believe @zsims is using it either. So don't make sense to create a separate org for it.

**Comment by zsims** [comment]
SGTM

It's a great project, and archiving will preserve that.

**Comment by mr-beerkiss** [comment]
Thanks for the input. I'll go ahead and archive.
